import type { PhilosophicalConcept } from "./types"

export const philosophicalConcepts: PhilosophicalConcept[] = [
  {
    name: "Liberté",
    definition: "Capacité d'agir selon sa volonté, sans contrainte extérieure",
    examples: ["libre arbitre", "autonomie morale", "émancipation politique"],
    relatedPhilosophers: ["Sartre", "Rousseau", "Spinoza", "Kant", "Descartes"],
    keywords: ["libre", "liberté", "autonomie", "choix", "volonté", "contrainte", "déterminisme", "responsabilité"],
  },
  {
    name: "Vérité",
    definition: "Conformité de la pensée avec la réalité ou cohérence logique",
    examples: ["vérité scientifique", "vérité révélée", "relativisme"],
    relatedPhilosophers: ["Platon", "Descartes", "Nietzsche", "Kant", "Popper"],
    keywords: [
      "vrai",
      "vérité",
      "réalité",
      "connaissance",
      "certitude",
      "doute",
      "opinion",
      "savoir",
      "science",
      "illusion",
    ],
  },
  {
    name: "Conscience",
    definition: "Connaissance immédiate que l'esprit a de ses états et de ses actes",
    examples: ["conscience morale", "conscience de soi", "inconscient"],
    relatedPhilosophers: ["Descartes", "Freud", "Sartre", "Locke"],
    keywords: ["conscience", "esprit", "pensée", "réflexion", "subjectivité", "soi", "introspection"],
  },
  {
    name: "Bonheur",
    definition: "État de satisfaction complète et durable",
    examples: ["hédonisme", "eudémonisme", "ataraxie"],
    relatedPhilosophers: ["Épicure", "Aristote", "Kant", "Pascal"],
    keywords: ["bonheur", "plaisir", "satisfaction", "bien-être", "joie", "désir", "sagesse", "finalité", "vertu"],
  },
  {
    name: "Justice",
    definition: "Principe moral fondé sur l'équité et le respect du droit",
    examples: ["justice distributive", "justice pénale", "égalité"],
    relatedPhilosophers: ["Platon", "Rousseau", "Rawls", "Hobbes"],
    keywords: ["juste", "justice", "équité", "droit", "égalité", "loi", "sanction"],
  },
  {
    name: "Morale",
    definition: "Ensemble des règles de conduite considérées comme bonnes",
    examples: ["impératif catégorique", "éthique de la vertu", "utilitarisme"],
    relatedPhilosophers: ["Kant", "Aristote", "Nietzsche", "Mill"],
    keywords: ["moral", "éthique", "bien", "mal", "devoir", "obligation", "responsabilité", "conscience morale"],
  },
  {
    name: "Travail",
    definition: "Activité humaine de transformation de la nature et de production",
    examples: ["aliénation", "division du travail", "technique"],
    relatedPhilosophers: ["Hegel", "Marx", "Arendt", "Bergson"],
    keywords: ["travail", "technique", "production", "aliénation", "activité", "effort", "transformation"],
  },
  {
    name: "Technique",
    definition: "Ensemble des procédés et moyens mis en œuvre pour transformer la nature",
    examples: ["progrès technique", "révolution industrielle", "intelligence artificielle"],
    relatedPhilosophers: ["Heidegger", "Simondon", "Ellul", "Descartes"],
    keywords: ["technique", "technologie", "outil", "progrès", "science", "nature", "intelligence", "machine"],
  },
  {
    name: "Langage",
    definition: "Système de signes permettant la communication et l'expression de la pensée",
    examples: ["langage naturel", "langage formel", "communication"],
    relatedPhilosophers: ["Wittgenstein", "Platon", "Rousseau", "Saussure"],
    keywords: ["langage", "langue", "parole", "communication", "expression", "signe", "symbole", "pensée"],
  },
  {
    name: "Société",
    definition: "Ensemble organisé d'individus vivant en communauté",
    examples: ["contrat social", "état de nature", "citoyenneté"],
    relatedPhilosophers: ["Hobbes", "Rousseau", "Locke", "Marx"],
    keywords: ["société", "social", "communauté", "pouvoir", "lois", "autorité", "citoyenneté", "État"],
  },
  {
    name: "Religion",
    definition: "Système de croyances et de pratiques relatives au sacré",
    examples: ["foi et raison", "révélation", "athéisme"],
    relatedPhilosophers: ["Pascal", "Spinoza", "Descartes", "Nietzsche"],
    keywords: ["religion", "religieux", "foi", "raison", "révélation", "transcendance", "athéisme", "divin"],
  },
  {
    name: "Nature",
    definition: "Ensemble des êtres et phénomènes du monde physique",
    examples: ["loi naturelle", "état de nature", "écologie"],
    relatedPhilosophers: ["Rousseau", "Descartes", "Darwin", "Lévi-Strauss"],
    keywords: ["nature", "naturel", "environnement", "loi naturelle", "culture", "instinct", "écologie"],
  },
  {
    name: "Art",
    definition: "Création d'œuvres à visée esthétique ou expressive",
    examples: ["beauté", "création artistique", "esthétique"],
    relatedPhilosophers: ["Kant", "Hegel", "Platon", "Nietzsche"],
    keywords: ["art", "beauté", "esthétique", "création", "œuvre", "imitation", "émotion", "jugement"],
  },
  {
    name: "Temps",
    definition: "Dimension dans laquelle se succèdent les événements",
    examples: ["durée", "éternité", "temporalité"],
    relatedPhilosophers: ["Saint Augustin", "Bergson", "Heidegger"],
    keywords: ["temps", "durée", "temporel", "éternité", "instant", "présent", "mémoire", "devenir"],
  },
  {
    name: "Mort",
    definition: "Cessation définitive de la vie",
    examples: ["finitude", "immortalité", "angoisse de la mort"],
    relatedPhilosophers: ["Épicure", "Heidegger", "Sartre", "Pascal"],
    keywords: ["mort", "mortel", "finitude", "immortalité", "peur", "existence", "vie"],
  },
  {
    name: "Culture",
    definition: "Ensemble des connaissances et pratiques acquises par l'homme en société",
    examples: ["civilisation", "éducation", "tradition"],
    relatedPhilosophers: ["Kant", "Lévi-Strauss", "Rousseau"],
    keywords: ["culture", "culturel", "apprentissage", "civilisation", "coutume", "progrès", "éducation"],
  },
  {
    name: "Inconscient",
    definition: "Ensemble des processus psychiques échappant à la conscience",
    examples: ["refoulement", "rêves", "lapsus"],
    relatedPhilosophers: ["Freud", "Jung", "Lacan"],
    keywords: ["inconscient", "pulsion", "refoulement", "symboles", "rêves", "psychanalyse"],
  },
  {
    name: "Existence",
    definition: "Le fait d'être, d'avoir une réalité",
    examples: ["condition humaine", "absurdité", "authenticité"],
    relatedPhilosophers: ["Camus", "Sartre", "Kierkegaard", "Heidegger"],
    keywords: ["existence", "existant", "être", "condition humaine", "absurdité", "sens", "authenticité"],
  },
  {
    name: "Désir",
    definition: "Mouvement vers un objet que l'on imagine source de satisfaction",
    examples: ["besoin et désir", "manque", "passion"],
    relatedPhilosophers: ["Épicure", "Platon", "Spinoza", "Schopenhauer"],
    keywords: ["désir", "besoin", "manque", "passion", "frustration", "satisfaction", "volonté"],
  },
  {
    name: "Science",
    definition: "Ensemble de connaissances obtenues par observation et raisonnement",
    examples: ["méthode expérimentale", "objectivité", "paradigme"],
    relatedPhilosophers: ["Galilée", "Popper", "Bachelard", "Descartes"],
    keywords: ["science", "scientifique", "méthode", "expérimentation", "objectivité", "hypothèse", "théorie"],
  },
  {
    name: "Autrui",
    definition: "L'autre personne considérée dans sa différence et sa similitude",
    examples: ["reconnaissance", "altérité", "empathie"],
    relatedPhilosophers: ["Levinas", "Sartre", "Hegel", "Rousseau"],
    keywords: ["autrui", "autre", "relation", "reconnaissance", "empathie", "altérité", "intersubjectivité"],
  },
  {
    name: "Raison",
    definition: "Faculté de penser, de juger et de connaître",
    examples: ["rationalisme", "logique", "argumentation"],
    relatedPhilosophers: ["Descartes", "Kant", "Hegel", "Aristote"],
    keywords: ["raison", "rationnel", "logique", "raisonnement", "pensée", "intelligence", "jugement"],
  },
  {
    name: "Passion",
    definition: "État affectif intense qui domine la raison",
    examples: ["amour", "colère", "ambition"],
    relatedPhilosophers: ["Descartes", "Spinoza", "Hume", "Kant"],
    keywords: ["passion", "émotion", "sentiment", "affection", "amour", "colère", "désir"],
  },
  {
    name: "Devoir",
    definition: "Obligation morale qui s'impose à la conscience",
    examples: ["impératif catégorique", "obligation", "responsabilité"],
    relatedPhilosophers: ["Kant", "Jonas", "Levinas", "Sartre"],
    keywords: ["devoir", "obligation", "moral", "responsabilité", "impératif", "conscience morale"],
  },
]

export const randomSubjects = [
  "La liberté est-elle une illusion ?",
  "Peut-on dire que la vérité est relative ?",
  "La justice n'est-elle qu'un rapport de force ?",
  "Le bonheur est-il le but de l'existence ?",
  "Sommes-nous responsables de nos actes inconscients ?",
  "Autrui est-il un obstacle à ma liberté ?",
  "Y a-t-il des devoirs envers soi-même ?",
  "Le temps nous appartient-il ?",
  "L'art nous éloigne-t-il de la réalité ?",
  "Le travail libère-t-il l'homme ?",
  "Faut-il avoir peur de la mort ?",
  "La technique nous rend-elle plus libres ?",
  "Peut-on vivre sans croyances ?",
  "L'État limite-t-il la liberté ?",
  "La culture nous humanise-t-elle ?",
  "La science peut-elle tout expliquer ?",
  "Le désir est-il la marque de notre imperfection ?",
  "Peut-on échapper à sa culture ?",
  "L'inconscient excuse-t-il ?",
  "Faut-il préférer le bonheur à la vérité ?",
  "La morale a-t-elle sa place en politique ?",
  "Le langage trahit-il la pensée ?",
  "Peut-on maîtriser la technique ?",
  "La religion est-elle l'opium du peuple ?",
  "Sommes-nous naturellement sociables ?",
  "L'art a-t-il pour fonction d'être beau ?",
  "Le présent existe-t-il ?",
  "Peut-on apprendre à mourir ?",
  "Qu'est-ce qui fait la valeur d'une culture ?",
  "L'existence précède-t-elle l'essence ?",
]
